title: 'Gluu Authorization Server'
favicon: https://www.gluu.org/wp-content/uploads/2020/01/Gluu-Green-Icon-64.png
buttons:
  - b0:
    text: Installer
    href: /gluu4/cloud-native-edition
  - b1:
    text: Instructions
    href: /gluu4/cloud-native-edition/pygluu/kubernetes/templates/helm
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme