# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: config
version: 1.8.40
kubeVersion: ">=v1.22.0-0"
description: Configuration parameters for setup and initial configuration secret and config layers used by Gluu services.
type: application
keywords:
  - configuration
  - secrets
home: https://gluu.org/docs/gluu-server/reference/container-configs/
sources:
  - https://gluu.org/docs/gluu-server/reference/container-configs/
  - https://github.com/GluuFederation/gluu4/tree/4.5/cloud-native-edition
maintainers:
  - name: Mohammad Abudayyeh
    email: support@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "4.5.6"
