# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: fido2
version: 4.5.6
kubeVersion: ">=v1.22.0-0"
description: FIDO 2.0 (FIDO2) is an open authentication standard that enables leveraging common devices to authenticate to online services in both mobile and desktop environments.
type: application
keywords:
  - fido2
  - u2f
home: https://gluu.org/docs/gluu-server/
sources:
  - https://gluu.org/docs/gluu-server/
  - https://github.com/GluuFederation/gluu4/tree/4.5/cloud-native-edition
maintainers:
  - name: Mohammad Abudayyeh
    email: support@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "4.5.6"
