# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: oxpassport
version: 4.5.6
kubeVersion: ">=v1.22.0-0"
description: Gluu interface to Passport.js to support social login and inbound identity.
type: application
keywords:
  - Passport.js
  - Inbound Identity
  - Social login
home: https://gluu.org/docs/gluu-server
sources:
  - https://github.com/GluuFederation/gluu4/tree/4.5/cloud-native-edition
maintainers:
  - name: Mohammad Abudayyeh
    email: support@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "4.5.6"
