name: build-pygluu
# This builds, packages and releases pygluu-kubernetes
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  publish:
    permissions:
      contents: write
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            artifact_name: pygluu-kubernetes.pyz
            asset_name: pygluu-kubernetes-linux-amd64.pyz
          #- os: macos-latest
          #  artifact_name: pygluu-kubernetes.pyz
          #  asset_name: pygluu-kubernetes-macos-amd64.pyz
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install jq cffi

    - name: Lint with flake8
      working-directory: ./cloud-native-edition
      run: |
        pip3 install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build pygluu
      working-directory: ./cloud-native-edition
      run: |
        sudo apt-get update || brew install jq
        sudo apt-get install build-essential || echo "Maybe im on macor OS"
        pip3 install shiv
        make zipapp

    - name: Get project
      id: project
      run: |
        echo "gituser=$(python3 -c 'import os ; REPO = os.environ.get("GITHUB_REPOSITORY") ; print(str(REPO).split("/")[0])')" >> $GITHUB_OUTPUT
        echo "gitproject=$(python3 -c 'import os ; REPO = os.environ.get("GITHUB_REPOSITORY") ; print(str(REPO).split("/")[1])')" >> $GITHUB_OUTPUT

    - name: Get latest tag and print version
      id: previoustag
      run: |
        echo "tag=$(curl https://api.github.com/repos/${{ steps.project.outputs.gituser }}/${{ steps.project.outputs.gitproject }}/releases/latest -s | grep "tag_name" | cut -d '"' -f 4)" >> $GITHUB_OUTPUT
        echo "${{ steps.previoustag.outputs.tag }}"


    - name: upload
      id: sha
      working-directory: ./cloud-native-edition
      run: |
        TAG=$(echo ${{ github.event.ref }} | cut -d '/' -f 3)
        VERSION="${TAG}"
        mv ${{ matrix.artifact_name }} ${{ matrix.asset_name }}
        sha256sum ${{ matrix.asset_name }} > ${{ matrix.asset_name }}.sha256sum
        echo "${{ secrets.MOWORKFLOWTOKEN }}" | gh auth login --with-token
        gh release upload "${VERSION}" *.pyz *.sha256sum
